spring:
  application:
    name: add

  data:
    mongodb:
      uri: mongodb+srv://nmtruong:nmtruong@domaincluster.0ioe4.mongodb.net/project_ex?retryWrites=true&w=majority&appName=DomainCluster

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8283

application:
  security:
    jwt:
      secret-key: beginsecret-queryString-283bduhia378-endsecret
      expiration-access: 86400000
      expiration-refresh: 604800000
